# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mr. De la Cruz
email: your-email@domain.com
description: Justin De La Cruz - Ontario Certified Teacher
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://teacherdlc.com" # the base hostname & protocol for your site
twitter_username: teacherdlc
instagram_username: mr.delacruz
facebook_username: teacherdlc
linkedin_username: justin-de-la-cruz-49357851
github_username:  teacherdlc

# Build settings
markdown: kramdown
